package com.example.ecommerce.db.mapper;

import com.example.ecommerce.db.bean.Cart;
import com.example.ecommerce.db.bean.CartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    long countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int deleteByPrimaryKey(Long cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int insert(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int insertSelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    Cart selectByPrimaryKey(Long cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByExampleSelective(@Param("row") Cart row, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByExample(@Param("row") Cart row, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByPrimaryKeySelective(Cart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByPrimaryKey(Cart row);
}