package com.example.ecommerce.db.mapper;

import com.example.ecommerce.db.bean.OrderItem;
import com.example.ecommerce.db.bean.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int deleteByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int insert(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int insertSelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    OrderItem selectByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByExampleSelective(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByExample(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByPrimaryKeySelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    int updateByPrimaryKey(OrderItem row);
}