package com.example.ecommerce.db.mapper;

import com.example.ecommerce.db.bean.Payment;
import com.example.ecommerce.db.bean.PaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    long countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int deleteByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int deleteByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int insert(Payment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int insertSelective(Payment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    List<Payment> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    Payment selectByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int updateByExampleSelective(@Param("row") Payment row, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int updateByExample(@Param("row") Payment row, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int updateByPrimaryKeySelective(Payment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Wed Jan 18 23:43:00 ICT 2023
     */
    int updateByPrimaryKey(Payment row);
}