package com.example.ecommerce.db.mapper;

import com.example.ecommerce.db.bean.ProductCategory;
import com.example.ecommerce.db.bean.ProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    long countByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int deleteByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int deleteByPrimaryKey(Long productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int insert(ProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int insertSelective(ProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    List<ProductCategory> selectByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    ProductCategory selectByPrimaryKey(Long productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int updateByExampleSelective(@Param("row") ProductCategory row, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int updateByExample(@Param("row") ProductCategory row, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int updateByPrimaryKeySelective(ProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Tue Jan 17 00:34:23 WIB 2023
     */
    int updateByPrimaryKey(ProductCategory row);
}