package com.example.ecommerce.db.mapper;

import com.example.ecommerce.db.bean.TransactionOrder;
import com.example.ecommerce.db.bean.TransactionOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    long countByExample(TransactionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int deleteByExample(TransactionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int insert(TransactionOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int insertSelective(TransactionOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    List<TransactionOrder> selectByExample(TransactionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    TransactionOrder selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int updateByExampleSelective(@Param("row") TransactionOrder row, @Param("example") TransactionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int updateByExample(@Param("row") TransactionOrder row, @Param("example") TransactionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int updateByPrimaryKeySelective(TransactionOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_order
     *
     * @mbg.generated Sat Jan 21 17:34:11 ICT 2023
     */
    int updateByPrimaryKey(TransactionOrder row);
}