package com.example.ecommerce.db.mapper;

import com.example.ecommerce.db.bean.TransactionPayment;
import com.example.ecommerce.db.bean.TransactionPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    long countByExample(TransactionPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int deleteByExample(TransactionPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int deleteByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int insert(TransactionPayment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int insertSelective(TransactionPayment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    List<TransactionPayment> selectByExample(TransactionPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    TransactionPayment selectByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int updateByExampleSelective(@Param("row") TransactionPayment row, @Param("example") TransactionPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int updateByExample(@Param("row") TransactionPayment row, @Param("example") TransactionPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int updateByPrimaryKeySelective(TransactionPayment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_payment
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    int updateByPrimaryKey(TransactionPayment row);
}