version: '3'
services:
  ecommerce:
    container_name: ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/ecommerce
    ports:
      - "8888:8888"
    links:
      - mongodb
    depends_on:
      - mongodb
      - mysqldb
    restart: on-failure
    networks:
      - ecommerce_network
  mysqldb:
    container_name: ecommerce_mysqldb
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      - ecommerce_network
  mongodb:
    image: mongo
    container_name: ecommerce_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce_network
volumes:
  mysqldb_data:
  mongodb_data:
networks:
  ecommerce_network: