package com.example.ecommerce.db.bean;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.cart_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Long cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.customer_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.quantity
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.cart_id
     *
     * @return the value of cart.cart_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Long getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.cart_id
     *
     * @param cartId the value for cart.cart_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.customer_id
     *
     * @return the value of cart.customer_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.customer_id
     *
     * @param customerId the value for cart.customer_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.product_id
     *
     * @return the value of cart.product_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.product_id
     *
     * @param productId the value for cart.product_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.quantity
     *
     * @return the value of cart.quantity
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.quantity
     *
     * @param quantity the value for cart.quantity
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}