package com.example.ecommerce.db.bean;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_id
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    private Long paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_method
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    private String paymentMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_status
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    private String paymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.order_id
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    private Long orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_id
     *
     * @return the value of payment.payment_id
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_id
     *
     * @param paymentId the value for payment.payment_id
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_method
     *
     * @return the value of payment.payment_method
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_method
     *
     * @param paymentMethod the value for payment.payment_method
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_status
     *
     * @return the value of payment.payment_status
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_status
     *
     * @param paymentStatus the value for payment.payment_status
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus == null ? null : paymentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.order_id
     *
     * @return the value of payment.order_id
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.order_id
     *
     * @param orderId the value for payment.order_id
     *
     * @mbg.generated Thu Jan 19 15:23:10 ICT 2023
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
}