package com.example.ecommerce.db.bean;

import java.math.BigDecimal;
import java.util.Date;

public class TransactionOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_order.order_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_order.order_date
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_order.total_price
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_order.status
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_order.customer_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_order.created_at
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_order.updated_at
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_order.order_id
     *
     * @return the value of transaction_order.order_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_order.order_id
     *
     * @param orderId the value for transaction_order.order_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_order.order_date
     *
     * @return the value of transaction_order.order_date
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_order.order_date
     *
     * @param orderDate the value for transaction_order.order_date
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_order.total_price
     *
     * @return the value of transaction_order.total_price
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_order.total_price
     *
     * @param totalPrice the value for transaction_order.total_price
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_order.status
     *
     * @return the value of transaction_order.status
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_order.status
     *
     * @param status the value for transaction_order.status
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_order.customer_id
     *
     * @return the value of transaction_order.customer_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_order.customer_id
     *
     * @param customerId the value for transaction_order.customer_id
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_order.created_at
     *
     * @return the value of transaction_order.created_at
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_order.created_at
     *
     * @param createdAt the value for transaction_order.created_at
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_order.updated_at
     *
     * @return the value of transaction_order.updated_at
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_order.updated_at
     *
     * @param updatedAt the value for transaction_order.updated_at
     *
     * @mbg.generated Sun Jan 22 17:40:26 ICT 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}